### ISSUE TITLE
Is "next holiday" inclusive?

### ISSUE THREAD

**Issue by ceramicskull** [pcraig3/hols#99]
Is next holiday inclusive?
For example if I open this API on labor day, will labor day be listed as the next holiday, or will it say thanksgiving? 
It would be nice if it was inclusive, I'm just trying to use your api to determine whether the current day is a holiday or not.

**Comment by pcraig3** [comment]
Hi there!

The answer is yes-ish. The actual comparison is done in [`getNextHoliday`](https://github.com/pcraig3/hols/blob/main/src/queries/index.js#L73-L81), which uses  a greater than or equal comparison. On the UI, I show the relative number of days using [`relativeDate`](https://github.com/pcraig3/hols/blob/main/src/dates/index.js#L145-L162), which will say "it's today!" if the 'next' holidays is today. (see pic)

<img width="481" alt="Screen Shot 2021-09-01 at 01 02 44" src="https://user-images.githubusercontent.com/2454380/131591052-84ad83f9-3a2b-4142-a082-ba89cebce60d.png">

However, I've built Canada Holidays as a server-rendered app (and API calls are always server-based as well), so to make that comparison it uses the EST timezone (I'm pretty sure). The date of a given holiday never includes time information (holidays always start at midnight), but in order to decide what time it is _right now_, the server has to make a decision about what timezone it's in. So if it's 1:00 am in Toronto, it's still 11:00 pm the day before in Edmonton.  Basically, if you are in Vancouver (3 hours behind), you won't see "it's today" after 9 pm, whereas if you're on the east coast, it ends up being there a couple hours longer. 

But the edge cases all fall outside of conventional working hours, so if that doesn't matter to you, you can just assume that it's inclusive (which is what I do).

**Comment by pcraig3** [comment]
Feel free to close the issue if that answers your question.

**Comment by ceramicskull** [comment]
I think it should be fine then as I am also in EST. Might be something to keep in mind for the future though, time zones are always tricky. Thanks for the info!
